[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
nixPkgs = ["pnpm"]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd apps/api && pnpm build"]

[start]
cmd = "cd apps/api && pnpm start"
